--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MyFreds/EnchantedBookShop
build-by-default: true
branches:
- main
projects:
  EnchantedBookShop:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: Muqsit/InvMenu/InvMenu
        version: ^4.6.5
    lint:
      phpstan: false
...
